# -*- coding: utf-8 -*-

from pathlib import Path
import os
import sys

source_dir = str(Path(__file__).parent.parent.absolute())
sys.path.insert(0, str(source_dir))
cur_dir = os.getcwd()
os.chdir(source_dir)
try:
    import versioneer

    versioneer.VCS = 'git'
    versioneer.versionfile_source = str(Path(source_dir, 'datacube_query/_version.py'))
    versioneer.versionfile_build = str(Path(source_dir, 'datacube_query/_version.py'))
    versioneer.tag_prefix = 'datacube_query-'
    versioneer.parentdir_prefix = source_dir  # '..'

    __version = versioneer.get_version().replace('.dirty', '')

    del versioneer
finally:
    os.chdir(cur_dir)

# -- General configuration ---------------------------------------------------
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'


